- name: var preference
  hosts: local
  connection: local
  vars:
    NAME: Message from play vars
  vars_files:
    - vars.yaml
  vars_prompt:
    - name: NAME
      prompt: Enter your name
      private: false
  tasks:
    - name: print name
      ansible.builtin.debug:
        msg: "Hi {{ NAME }}" 