- name: Number check
  hosts: local
  connection: local
  vars_prompt:
   - name:  NUMBER_IS
     prompt: Enter Number
     private:  false
  tasks:
   - name: print the number
     ansible.builtin.debug:
       msg: "Given number is greater than 5"
     when: NUMBER_IS | int > 5


     